openapi: 3.0.0
info:
  title: mycart
  version: 1.0.0
servers:
  - url: http://localhost:5000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: User
  - name: Product
  - name: Cart
  - name: Vendor
  - name: Order
paths:
  /users/login:
    post:
      tags:
        - User
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ade@gmail.com
                username: adedunmola.szn
                password: password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/register:
    post:
      tags:
        - User
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: ade
                last_name: ade
                email: ade@gmail.com
                username: adedunmola.szn
                password: password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/verify:
    post:
      tags:
        - User
      summary: Verify User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 28
                otp: '9514'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/logout:
    get:
      tags:
        - User
      summary: Logout User
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/refresh:
    get:
      tags:
        - User
      summary: Get New Access Token
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products:
    post:
      tags:
        - Product
      summary: Create New Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: canon cam 450s pro
                details: best canon cam in the market yet
                price: 40
                category: gadget
                quantity: 100
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products/:
    get:
      tags:
        - Product
      summary: Get All Products
      security:
        - bearerAuth: []
      parameters:
        - name: category
          in: query
          schema:
            type: string
          example: gadget
        - name: min_price
          in: query
          schema:
            type: integer
          example: '40'
        - name: sort_by
          in: query
          schema:
            type: string
          example: price-desc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carts/add-item:
    post:
      tags:
        - Cart
      summary: Add Item to Cart
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: query
          schema:
            type: integer
          example: '1'
        - name: quantity
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /carts/:
    get:
      tags:
        - Cart
      summary: Get Cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /vendors/register:
    post:
      tags:
        - Vendor
      summary: Vendors Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: some_user
                last_name: test_user
                username: test_username
                email: vendor@gmail.com
                password: '123456789'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - Order
      summary: Create New Order
      security:
        - bearerAuth: []
      parameters:
        - name: cart_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}